---
- hosts: applicationservers
  become: yes
  gather_facts: true
  vars:
    packages:
      - openjdk-11-jdk
      - openjdk-11-jre 
      - maven -y   
  tasks: 

    - name: "Install java and maven"
      apt: 
        name: "{{packages}}"
        state: present
   
    
   
 
    